### ISSUE TITLE
CPU compatibility?

### ISSUE THREAD

**Issue by eannaf** [simongraham/hovernet_inference#24]
Hi.
I have no access to a GPU and just want to infer a small ROI. I've used tensorflow instead of tensorflow-gpu. However, I'm having an issue with data format in the conv layer. The CPU can only handle NHWC and the data format in the network seems to be NCHW. Yet my mini_batch and sub-patches are in NHWC format. Is this model compatible with a CPU? I'm getting the following error:

```
tensorflow.python.framework.errors_impl.UnimplementedError: Generic conv implemetation only supports NHWC tensor format for now.
[[{{node conv0/Conv2D}} = Conv2D[T=DT_FLOAT, data_foramt="NCHW", dilation=[1,1,1,1], padding="SAME", strides=[1,1,1,1], use_cudnn_on_gpu=true, _device="/job:localhost/replica:0/task:0/device:CPU:0"](truediv, conv0/W/read)]]
```

Thanks

**Comment by simongraham** [comment]
Thanks for reaching out. I have noted this and will look into this within the next few days.

**Comment by simongraham** [comment]
The issue is that the layers in the code is in the `NCHW` format, which is not supported on the CPU. Look at [this issue](https://github.com/tensorpack/tensorpack/issues/1024) from the tensorpack GitHub page for more information. To change to `NHWC`, you will need to modify the code to account for this. 

For example, you will need to change the format [here](https://github.com/simongraham/hovernet_inference/blob/master/hover/model/graph.py#L113), change to `'channels_last'` [here](https://github.com/simongraham/hovernet_inference/blob/master/hover/model/graph.py#L13) and comment out [this line](https://github.com/simongraham/hovernet_inference/blob/master/hover/model/graph.py#L100). There may also be some additional tweaks that you will need to apply. Using the CPU won't be feasible for processing images and we would really recommend using the code in it's current format and using a GPU.

**Comment by eannaf** [comment]
Cheers Simon. I got this working. Just needed to check the format at every stage. I'd be happy to share if you wanted to add a CPU compatibility?

Also, the inference is limited to 6 classes in that model. From what I can say, this doesn't allow muscle cells to be differentiated from fibroblasts, something which can you have shown in Figure 6 of the Hovernet paper. Does the model need to retrained to be able to take 7 classes as input?

**Comment by simongraham** [comment]
I'm pleased that you got it working on the CPU! We will limit this repo to a GPU implementation, but will keep the option for CPU compatibility open for future work - thanks!

In the original hovernet paper, we use 4 classes on the CoNSeP dataset: epithelial, inflammatory, spindle-shaped and miscellaneous. Here, we merged fibroblasts and muscle cells into a single class. In this repository, the ckpt provided is trained on the PanNuke dataset. This experiment was not included in the original paper, but can be found [here](https://arxiv.org/abs/2003.10778). If you wanted to output **all** classes from the CoNSeP dataset (we didn't do that in our original paper) then you would need to retrain, yes. Note, this repo applies a very subtle modification to the original architecture, which leads to the output size being of size `164x164` and therefore making it more efficient for WSI processing. 

We created this repo to enable researchers to use a model trained on a large dataset 'out of the box'. We didn't have retraining in mind for this.

**Comment by dannydjrs** [comment]
I've done the modifications shown by @simongraham however still cannot get this working on cpu and am getting the following error:

```
Traceback (most recent call last):
  File "run.py", line 638, in <module>
    infer.load_model() 
  File "run.py", line 163, in load_model
    self.predictor = OfflinePredictor(pred_config)
  File "/Users/dannydjrs/opt/anaconda3/envs/hovernet/lib/python3.6/site-packages/tensorpack/predict/base.py", line 148, in __init__
    config.tower_func(*input.get_input_tensors())
  File "/Users/dannydjrs/opt/anaconda3/envs/hovernet/lib/python3.6/site-packages/tensorpack/tfutils/tower.py", line 284, in __call__
    output = self._tower_fn(*args)
  File "/Users/dannydjrs/opt/anaconda3/envs/hovernet/lib/python3.6/site-packages/tensorpack/graph_builder/model_desc.py", line 162, in build_graph
    return self._build_graph(args)
  File "/Users/dannydjrs/code/hovernet_inference/hover/model/graph.py", line 133, in _build_graph
    np_feat = decoder('np', d)
  File "/Users/dannydjrs/code/hovernet_inference/hover/model/graph.py", line 74, in decoder
    u3_sum = tf.add_n([u3, i[-2]])
  File "/Users/dannydjrs/opt/anaconda3/envs/hovernet/lib/python3.6/site-packages/tensorflow_core/python/util/dispatch.py", line 180, in wrapper
    return target(*args, **kwargs)
  File "/Users/dannydjrs/opt/anaconda3/envs/hovernet/lib/python3.6/site-packages/tensorflow_core/python/ops/math_ops.py", line 3007, in add_n
    return gen_math_ops.add_n(inputs, name=name)
  File "/Users/dannydjrs/opt/anaconda3/envs/hovernet/lib/python3.6/site-packages/tensorflow_core/python/ops/gen_math_ops.py", line 477, in add_n
    "AddN", inputs=inputs, name=name)
  File "/Users/dannydjrs/opt/anaconda3/envs/hovernet/lib/python3.6/site-packages/tensorflow_core/python/framework/op_def_library.py", line 794, in _apply_op_helper
    op_def=op_def)
  File "/Users/dannydjrs/opt/anaconda3/envs/hovernet/lib/python3.6/site-packages/tensorflow_core/python/util/deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "/Users/dannydjrs/opt/anaconda3/envs/hovernet/lib/python3.6/site-packages/tensorflow_core/python/framework/ops.py", line 3357, in create_op
    attrs, op_def, compute_device)
  File "/Users/dannydjrs/opt/anaconda3/envs/hovernet/lib/python3.6/site-packages/tensorflow_core/python/framework/ops.py", line 3426, in _create_op_internal
    op_def=op_def)
  File "/Users/dannydjrs/opt/anaconda3/envs/hovernet/lib/python3.6/site-packages/tensorflow_core/python/framework/ops.py", line 1770, in __init__
    control_input_ops)
  File "/Users/dannydjrs/opt/anaconda3/envs/hovernet/lib/python3.6/site-packages/tensorflow_core/python/framework/ops.py", line 1610, in _create_c_op
    raise ValueError(str(e))
ValueError: Dimension 1 in both shapes must be equal, but are 2 and 1. Shapes are [?,2,64,1024] and [?,1,64,1024].
	From merging shape 0 with other shapes. for 'np/u3/AddN' (op: 'AddN') with input shapes: [?,2,64,1024], [?,1,64,1024].
```

Any chance @eannaf could show me what you did?

**Comment by stanleywkng** [comment]
Dear eannaf,

I are trying to run the hovernet_inference code using CPU as I do not currently have access to a GPU.
I ran into the same issue as you. Since you have already made the necessary edits to get the code to run on CPU, do you mind sharing it with me?

Many thanks,
Stan

**Comment by JoyLinWQ** [comment]
> The issue is that the layers in the code is in the `NCHW` format, which is not supported on the CPU. Look at [this issue](https://github.com/tensorpack/tensorpack/issues/1024) from the tensorpack GitHub page for more information. To change to `NHWC`, you will need to modify the code to account for this.
> 
> For example, you will need to change the format [here](https://github.com/simongraham/hovernet_inference/blob/master/hover/model/graph.py#L113), change to `'channels_last'` [here](https://github.com/simongraham/hovernet_inference/blob/master/hover/model/graph.py#L13) and comment out [this line](https://github.com/simongraham/hovernet_inference/blob/master/hover/model/graph.py#L100). There may also be some additional tweaks that you will need to apply. Using the CPU won't be feasible for processing images and we would really recommend using the code in it's current format and using a GPU.

Hi @simongraham , thanks for detailing the amends for changing NCHW to NHWC. I have followed your steps and have output below but unsure how to approach it. Could you please advise? I am using a .tif file that is 1000x1000. Thanks!

Input:
```
(hovernet_simon) PS C:\Users\jlwq0\Documents\hovernet_inference> python run.py --gpu='0' --mode='tile' --model='monusac.npz' --input_dir='tile_dir' --output_dir='output' --inf_tile_shape=400 --proc_tile_shape=256 --batch_size=1 --return_probs
```

Output:
```
{'--batch_size': '1',
 '--cache_dir': 'cache/',
 '--gpu': '0',
 '--help': False,
 '--inf_tile_shape': '400',
 '--input_dir': 'tile_dir',
 '--mode': 'tile',
 '--model': 'monusac.npz',
 '--output_dir': 'output',
 '--postproc_workers': '10',
 '--proc_tile_shape': '256',
 '--return_probs': True,
 '--version': False}
Loading Model...
Traceback (most recent call last):
  File "C:\Users\jlwq0\anaconda3\envs\hovernet_simon\lib\site-packages\tensorflow\python\framework\ops.py", line 1628, in _create_c_op
    c_op = c_api.TF_FinishOperation(op_desc)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Dimension 1 in both shapes must be equal, but are 2 and 1. Shapes are [?,2,64,1024] and [?,1,64,1024].
        From merging shape 0 with other shapes. for 'np/u3/AddN' (op: 'AddN') with input shapes: [?,2,64,1024], [?,1,64,1024].

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "run.py", line 859, in <module>
    infer.load_model()
  File "run.py", line 208, in load_model
    self.predictor = OfflinePredictor(pred_config)
  File "C:\Users\jlwq0\anaconda3\envs\hovernet_simon\lib\site-packages\tensorpack\predict\base.py", line 148, in __init__
    config.tower_func(*input.get_input_tensors())
  File "C:\Users\jlwq0\anaconda3\envs\hovernet_simon\lib\site-packages\tensorpack\tfutils\tower.py", line 284, in __call__
    output = self._tower_fn(*args)
  File "C:\Users\jlwq0\anaconda3\envs\hovernet_simon\lib\site-packages\tensorpack\graph_builder\model_desc.py", line 162, in build_graph
    return self._build_graph(args)
  File "C:\Users\jlwq0\Documents\hovernet_inference\hover\model\graph.py", line 133, in _build_graph
    np_feat = decoder('np', d)
  File "C:\Users\jlwq0\Documents\hovernet_inference\hover\model\graph.py", line 74, in decoder
    u3_sum = tf.add_n([u3, i[-2]])
  File "C:\Users\jlwq0\anaconda3\envs\hovernet_simon\lib\site-packages\tensorflow\python\ops\math_ops.py", line 2173, in add_n
    return gen_math_ops.add_n(inputs, name=name)
  File "C:\Users\jlwq0\anaconda3\envs\hovernet_simon\lib\site-packages\tensorflow\python\ops\gen_math_ops.py", line 372, in add_n
    "AddN", inputs=inputs, name=name)
  File "C:\Users\jlwq0\anaconda3\envs\hovernet_simon\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "C:\Users\jlwq0\anaconda3\envs\hovernet_simon\lib\site-packages\tensorflow\python\util\deprecation.py", line 488, in new_func
    return func(*args, **kwargs)
  File "C:\Users\jlwq0\anaconda3\envs\hovernet_simon\lib\site-packages\tensorflow\python\framework\ops.py", line 3274, in create_op
    op_def=op_def)
  File "C:\Users\jlwq0\anaconda3\envs\hovernet_simon\lib\site-packages\tensorflow\python\framework\ops.py", line 1792, in __init__
    control_input_ops)
  File "C:\Users\jlwq0\anaconda3\envs\hovernet_simon\lib\site-packages\tensorflow\python\framework\ops.py", line 1631, in _create_c_op
    raise ValueError(str(e))
ValueError: Dimension 1 in both shapes must be equal, but are 2 and 1. Shapes are [?,2,64,1024] and [?,1,64,1024].
        From merging shape 0 with other shapes. for 'np/u3/AddN' (op: 'AddN') with input shapes: [?,2,64,1024], [?,1,64,1024].
```
